/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.group6.factorySimulation;

import java.io.IOException;

public class App {
    private final TextView view;


    public App() {
        this.view = new TextView();
    }


    public static void main(String[] args) throws IOException {
        App app = new App();
        while (true) {
            app.view.displayOutput(app.view.promptUser());
        }
    }
}
