/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.group6.factorySimulation;

public class App {
    private final TextView view;


    public App() {
        this.view = new TextView();
    }


    public static void main(String[] args) {
        App app = new App();
        while (true) {
            app.view.displayOutput(System.out, app.view.promptUser(System.out));
        }
    }
}
