/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.duke.ece651.group6.factorySimulation;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
}
